version: '3'

services:
  frontend:
    build:
      context: ./client
    image: fadyamir/frontend
    env_file:
      - ./client/.env.production
    networks:
      - app-network
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 80s

  backend:
    build:
      context: ./server
    image: fadyamir/backend
    env_file:
      - ./server/.env.production
    environment:
      - NODE_ENV=production
    networks:
      - app-network
      - backend-network
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s

  database:
    volumes:
      - db-data:/data/db
    networks:
      - backend-network
    deploy:
      restart_policy:
        condition: on-failure

  nginx:
    volumes:
      - ./nginx/fake-ssl:/etc/nginx/ssl:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    secrets:
      - dhparam-secret
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf
      - source: nginx_default_conf
        target: /etc/nginx/conf.d/default.conf
    networks:
      - app-network
    deploy:
      restart_policy:
        condition: on-failure

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    networks:
      - app-network
    # command: certonly --staging --webroot --webroot-path=/var/www/html --email fadyamir223@gmail.com --agree-tos --no-eff-email -d example.com -d www.example.com

networks:
  app-network:
    driver: bridge # overlay
  backend-network:
    driver: bridge # overlay

volumes:
  db-data:
  certbot-etc:
  certbot-var:
  web-root:

configs:
  nginx_conf:
    file: ./nginx/nginx.conf
  nginx_default_conf:
    file: ./nginx/default.conf

secrets:
  dhparam-secret:
    file: ./nginx/dhparam/dhparam-2048.pem
